### ISSUE TITLE
Flicker issue when moving to next question of quiz

### ISSUE THREAD

**Issue by sassansh** [ProjectAurora-Tech/InfoConsolidation#14]
When you select an answer option on the quiz and it’s about to move to the next question, the next question flickers just below the current question before it fixes itself.

**Comment by sassansh** [comment]
Think I fixed it! Can someone test this please on the phase2-quiz branch:
https://github.com/campuslightbox/Campus-Lightbox/commit/ec7d909ba7bb0de353e4e9fa294b4343d4bed5c1
@Jrivera1625 @cching0L2

**Comment by Jrivera1625** [comment]
Tested and confirmed
